=== Mikael61/DH/spoilers/xmltest.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT brevsamling (brev)+>
<!ELEMENT brev ANY>
<!ELEMENT brevhuvud (#PCDATA)>
<!ELEMENT salutering (#PCDATA)>
<!ELEMENT stycke (#PCDATA|sidstart|nyrad)*>
<!ELEMENT poesi (versrad)+>
<!ELEMENT avslutningsfras (#PCDATA)>
<!ELEMENT signatur (#PCDATA)>
<!ELEMENT sidstart EMPTY>
<!ELEMENT nyrad EMPTY>
<!ELEMENT versrad (#PCDATA)>
<!ATTLIST sidstart sidnummer CDATA #REQUIRED>

=== Mikael61/DH/spoilers/brev.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE brevsamling SYSTEM "xmltest.dtd">
<brevsamling>
    <brev>
        <sidstart sidnummer="1"/>
        <brevhuvud>Craiglockhart. July 1917. Wednesday </brevhuvud>
        <salutering>Dear L.</salutering>
        <stycke>Thanks for yours of this morning. I hope you have had my card posted last Monday. On
            Mond. next I lecture the Field Club - a Nat. Hist. Association, in the lines of our old
            Society - Geological, (you + me) + Botanical (New) Do you remember: you old Black Molt?
            Well, the days have come when I am one of the founders of a real learned society. My
            oubject has the rather journalese Title of "Do Plants Think?" - a study of the Response
            to Stimuli + Devices for Fertilisation, etc. I have no books yet, but I remember a
            number of useful points from your big Cassets' (I think it was Cassets') studied a 1911.
            Meanwhile <sidstart sidnummer="2"/> I'm beastly bothered with our Mag. (herewith) and
            I'm {take} German Lessons at the Berlitz, Edin. </stycke>
        <stycke>Last week I wrote (to order) a strong
            bit of Blank: on Antaeus v. Heracles. These are the best lines, methinks: (N.B. Antaeus
            deriving strength from his Mother Earth nearly licked old Herk.) </stycke>
        <poesi>
            <versrad>... How Earth herself empowered him with her trick,</versrad>
            <versrad>Gave him the grip and stringency of Winter,</versrad>
            <versrad>And all the ardour of th' invincible Spring;</versrad>
            <versrad>How all the blood of June glutted his heart,</versrad>
            <versrad>And all the glow of huge autumnal storms</versrad>
            <versrad>Stirred on his face, and flickered from his eyes.</versrad>
        </poesi>
        <stycke>I had seen your Song. May the music be equally happy. you are lucky! you shall have
            my Locke's "Usurper" if you will. Its now at home.  </stycke>
        <stycke>I see Swinburne also wrote a number
            of replicas of the olde Ballad! Heigh ho!</stycke>
        <avslutningsfras>Ever
            yours</avslutningsfras>
        <signatur>WEO </signatur>
    </brev>
</brevsamling>
